# Generated by Django 3.0.4 on 2020-04-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coogle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ing_type',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Herb', 'Herb'), ('Meat', 'Meat'), ('Fish', 'Fish'), ('Nut', 'Nut'), ('Fat', 'Fat'), ('Dairy', 'Dairy'), ('Carb', 'Carb'), ('Root', 'Root')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('ingredients', models.ManyToManyField(to='coogle.Ingredient')),
            ],
        ),
    ]
