# Generated by Django 3.0.4 on 2020-04-28 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coogle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ing_type',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Herb', 'Herb'), ('Meat', 'Meat'), ('Fish', 'Fish'), ('Nut', 'Nut'), ('Fat', 'Fat'), ('Dairy', 'Dairy'), ('Carb', 'Carb'), ('Root', 'Root')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('instructions', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('ingredients', models.ManyToManyField(to='coogle.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=10)),
                ('end_month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coogle.Ingredient')),
            ],
        ),
    ]
