# Generated by Django 3.0.4 on 2020-04-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coogle', '0002_auto_20200416_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
