# Generated by Django 3.0.4 on 2020-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_remove_statusmessage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2020-04-06 12:12'),
            preserve_default=False,
        ),
    ]
