# Generated by Django 3.0.4 on 2020-03-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200330_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='person',
        ),
    ]
