# Generated by Django 3.0.4 on 2020-03-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='person',
        ),
    ]
